package ajastin.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ajastin.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.14 12:13:54 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AjastinTest {
}