package ajastin.test;
// Generated by ComTest BEGIN
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import ajastin.*;
// Generated by ComTest END
import java.util.List;

/**
 * Test class made by ComTest
 * @version 2023.04.28 12:43:31 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PelitTest {



  // Generated by ComTest BEGIN
  /** 
   * testPoista52 
   * @throws SailoException when error
   */
  @Test
  public void testPoista52() throws SailoException {    // Pelit: 52
    Pelit pelit = new Pelit(); 
    Peli dota22 = new Peli(); dota22.lisaaPeli(3); 
    pelit.lisaa(dota22); 
    Peli dota24 = new Peli(); dota22.lisaaPeli(2); 
    pelit.lisaa(dota24); 
    Peli dota23 = new Peli(); dota23.lisaaPeli(1); 
    assertEquals("From: Pelit line: 61", false, pelit.poista(dota23)); assertEquals("From: Pelit line: 61", 2, pelit.getLkm()); 
    assertEquals("From: Pelit line: 62", true, pelit.poista(dota22)); assertEquals("From: Pelit line: 62", 1, pelit.getLkm()); 
    List<Peli> h = pelit.annaPelit(3); 
    assertEquals("From: Pelit line: 64", 0, h.size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoistaProfiilinPelit81 */
  @Test
  public void testPoistaProfiilinPelit81() {    // Pelit: 81
    Pelit pelit = new Pelit(); 
    Peli dota22 = new Peli(); dota22.lisaaPeli(2); 
    pelit.lisaa(dota22); 
    Peli dota24 = new Peli(); dota22.lisaaPeli(2); 
    pelit.lisaa(dota24); 
    Peli dota23 = new Peli(); dota23.lisaaPeli(1); 
    pelit.lisaa(dota23); 
    assertEquals("From: Pelit line: 89", 1, pelit.poistaProfiilinPelit(2)); assertEquals("From: Pelit line: 89", 2, pelit.getLkm()); 
    assertEquals("From: Pelit line: 90", 0, pelit.poistaProfiilinPelit(3)); assertEquals("From: Pelit line: 90", 2, pelit.getLkm()); 
    List<Peli> h = pelit.annaPelit(2); 
    assertEquals("From: Pelit line: 92", 0, h.size()); 
    h = pelit.annaPelit(1); 
    assertEquals("From: Pelit line: 94", dota23, h.get(0)); 
  } // Generated by ComTest END
}