package ajastin.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END
import ajastin.*;

/**
 * Test class made by ComTest
 * @version 2023.04.14 12:27:19 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PeliTest {



  // Generated by ComTest BEGIN
  /** testToString115 */
  @Test
  public void testToString115() {    // Peli: 115
    Peli peli = new Peli(); 
    peli.parse("2|2|Dota 2|1949"); 
    assertEquals("From: Peli line: 118", "2|2|Dota 2|1949", peli.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse132 */
  @Test
  public void testParse132() {    // Peli: 132
    Peli peli = new Peli(); 
    peli.parse("2|2|Dota|1949"); 
    assertEquals("From: Peli line: 135", 2, peli.getProfiiliNro()); 
    assertEquals("From: Peli line: 136", "2|2|Dota|1949", peli.toString()); 
    peli.rekisteroi(); 
    int n = peli.getTunnusNro(); 
    peli.parse(""+(n+20)); 
    peli.rekisteroi(); 
    assertEquals("From: Peli line: 142", n+20+1, peli.getTunnusNro()); 
    assertEquals("From: Peli line: 143", "" + (n+20+1) + "|2|Dota|1949", peli.toString()); 
  } // Generated by ComTest END
}