package ajastin.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END
import ajastin.*;

/**
 * Test class made by ComTest
 * @version 2023.04.28 12:43:52 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PeliTest {



  // Generated by ComTest BEGIN
  /** testToString117 */
  @Test
  public void testToString117() {    // Peli: 117
    Peli peli = new Peli(); 
    peli.parse("2|2|Dota 2|1949"); 
    assertEquals("From: Peli line: 120", "2|2|Dota 2|1949", peli.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse134 */
  @Test
  public void testParse134() {    // Peli: 134
    Peli peli = new Peli(); 
    peli.parse("2|2|Dota|1949"); 
    assertEquals("From: Peli line: 137", 2, peli.getProfiiliNro()); 
    assertEquals("From: Peli line: 138", "2|2|Dota|1949", peli.toString()); 
    peli.rekisteroi(); 
    int n = peli.getTunnusNro(); 
    peli.parse(""+(n+20)); 
    peli.rekisteroi(); 
    assertEquals("From: Peli line: 144", n+20+1, peli.getTunnusNro()); 
    assertEquals("From: Peli line: 145", "" + (n+20+1) + "|2|Dota|1949", peli.toString()); 
  } // Generated by ComTest END
}