package ajastin.test;
// Generated by ComTest BEGIN
import ajastin.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.28 13:17:22 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ProfiilitTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa45 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa45() throws SailoException {    // Profiilit: 45
    Profiilit Profiilit = new Profiilit(); 
    Profiili matti1 = new Profiili(), matti2 = new Profiili(); 
    assertEquals("From: Profiilit line: 49", 0, Profiilit.getLkm()); 
    Profiilit.lisaa(matti1); assertEquals("From: Profiilit line: 50", 1, Profiilit.getLkm()); 
    Profiilit.lisaa(matti2); assertEquals("From: Profiilit line: 51", 2, Profiilit.getLkm()); 
    Profiilit.lisaa(matti1); assertEquals("From: Profiilit line: 52", 3, Profiilit.getLkm()); 
    Profiilit.lisaa(matti1); assertEquals("From: Profiilit line: 53", 4, Profiilit.getLkm()); 
    Profiilit.lisaa(matti1); assertEquals("From: Profiilit line: 54", 5, Profiilit.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testProfiilitIterator211 
   * @throws SailoException when error
   */
  @Test
  public void testProfiilitIterator211() throws SailoException {    // Profiilit: 211
    Profiilit profiilit = new Profiilit(); 
    Profiili aku1 = new Profiili(), aku2 = new Profiili(); 
    aku1.rekisteroi(); aku2.rekisteroi(); 
    profiilit.lisaa(aku1); 
    profiilit.lisaa(aku2); 
    profiilit.lisaa(aku1); 
    StringBuffer ids = new StringBuffer(30); 
    for (Profiili jasen:profiilit) // Kokeillaan for-silmukan toimintaa
    ids.append(" "+jasen.getTunnusNro()); 
    String tulos = " " + aku1.getTunnusNro() + " " + aku2.getTunnusNro() + " " + aku1.getTunnusNro(); 
    assertEquals("From: Profiilit line: 230", tulos, ids.toString()); 
    ids = new StringBuffer(30); 
    for (Iterator<Profiili>  i=profiilit.iterator(); i.hasNext(); ) { // ja iteraattorin toimintaa
    Profiili jasen = i.next(); 
    ids.append(" "+jasen.getTunnusNro()); 
    }
    assertEquals("From: Profiilit line: 238", tulos, ids.toString()); 
    Iterator<Profiili>  i=profiilit.iterator(); 
    assertEquals("From: Profiilit line: 241", true, i.next() == aku1); 
    assertEquals("From: Profiilit line: 242", true, i.next() == aku2); 
    assertEquals("From: Profiilit line: 243", true, i.next() == aku1); 
    try {
    i.next(); 
    fail("Profiilit: 245 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsiId333 
   * @throws SailoException when error
   */
  @Test
  public void testEtsiId333() throws SailoException {    // Profiilit: 333
    Profiilit profiilit = new Profiilit(); 
    Profiili aku1 = new Profiili(), aku2 = new Profiili(), aku3 = new Profiili(); 
    aku1.rekisteroi(); aku2.rekisteroi(); aku3.rekisteroi(); 
    int id1 = aku1.getTunnusNro(); 
    profiilit.lisaa(aku1); profiilit.lisaa(aku2); profiilit.lisaa(aku3); 
    assertEquals("From: Profiilit line: 340", 1, profiilit.etsiId(id1+1)); 
    assertEquals("From: Profiilit line: 341", 2, profiilit.etsiId(id1+2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista359 
   * @throws SailoException when error
   */
  @Test
  public void testPoista359() throws SailoException {    // Profiilit: 359
    Profiilit profiilit = new Profiilit(); 
    Profiili aku1 = new Profiili(), aku2 = new Profiili(), aku3 = new Profiili(); 
    aku1.rekisteroi(); aku2.rekisteroi(); aku3.rekisteroi(); 
    int id1 = aku1.getTunnusNro(); 
    profiilit.lisaa(aku1); profiilit.lisaa(aku2); profiilit.lisaa(aku3); 
    assertEquals("From: Profiilit line: 366", 1, profiilit.poista(id1+1)); 
    assertEquals("From: Profiilit line: 367", null, profiilit.annaId(id1+1)); assertEquals("From: Profiilit line: 367", 2, profiilit.getLkm()); 
    assertEquals("From: Profiilit line: 368", 1, profiilit.poista(id1)); assertEquals("From: Profiilit line: 368", 1, profiilit.getLkm()); 
    assertEquals("From: Profiilit line: 369", 0, profiilit.poista(id1+3)); assertEquals("From: Profiilit line: 369", 1, profiilit.getLkm()); 
  } // Generated by ComTest END
}