package Ht.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ajastin.Profiili;
import Ht.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.28 14:57:48 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TietueTest {



  // Generated by ComTest BEGIN
  /** testInt17 */
  @Test
  public void testInt17() {    // Tietue: 17
    Profiili har = new Profiili(); 
    assertEquals("From: Tietue line: 20", 3, har.getKenttia()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testInt29 */
  @Test
  public void testInt29() {    // Tietue: 29
    Profiili har = new Profiili(); 
    assertEquals("From: Tietue line: 31", 1, har.ekaKentta()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString41 */
  @Test
  public void testString41() {    // Tietue: 41
    Profiili har = new Profiili(); 
    assertEquals("From: Tietue line: 43", "nickName", har.getKysymys(2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString53 */
  @Test
  public void testString53() {    // Tietue: 53
    Profiili har = new Profiili(); 
    har.parse("   2   |  Eetu Alanen  |   Tsuppi "); 
    assertEquals("From: Tietue line: 56", "2", har.anna(0)); 
    assertEquals("From: Tietue line: 57", "Eetu Alanen", har.anna(1)); 
    assertEquals("From: Tietue line: 58", "Tsuppi", har.anna(2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTietue80 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testTietue80() throws CloneNotSupportedException {    // Tietue: 80
    Profiili har = new Profiili(); 
    har.parse("   2   |  10  |   Kalastus  | 1949 | 22 t "); 
    Object kopio = har.clone(); 
    assertEquals("From: Tietue line: 85", har.toString(), kopio.toString()); 
    har.parse("   1   |  11  |   Uinti  | 1949 | 22 t "); 
    assertEquals("From: Tietue line: 87", false, kopio.toString().equals(har.toString())); 
    assertEquals("From: Tietue line: 88", true, kopio instanceof Profiili); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString98 */
  @Test
  public void testString98() {    // Tietue: 98
    Profiili Profiili = new Profiili(); 
    Profiili.parse("   0   |  Eetu Alanen  |   Tsuppi  "); 
  } // Generated by ComTest END
}